import { Service } from './types';

export const SERVICES: Service[] = [
  {
    id: 'techafrik',
    title: 'TechAfrik',
    tagline: 'AI & Blockchain Media for Africa',
    description: 'AI & Blockchain Media for Africa. Delivering tech education, news, and insights across Telegram, WhatsApp, TikTok, Instagram, LinkedIn & X.',
    longDescription: 'TechAfrik is the leading AI and blockchain media platform for Africa. We deliver daily tech education, breaking news, and deep insights to thousands of Africans across every major social platform — Telegram, WhatsApp, TikTok, Instagram, LinkedIn, and X. Our mission is to make blockchain and AI literacy accessible to every African, regardless of background or location.',
    icon: 'Cpu',
    category: 'Media & Education',
    color: '#F5A623',
    externalLink: 'https://techafrik.rpnmore.com',
    features: [
      'Daily AI & blockchain news across 6 platforms',
      'Crypto education for African beginners',
      'Market analysis & trading insights',
      'Community of 10,000+ African tech enthusiasts',
      'Telegram & WhatsApp broadcast channels',
      'TikTok & Instagram video education',
    ],
    additionalInfo: 'TechAfrik operates 24/7 and publishes multiple updates per day across all channels. Our team of researchers and analysts monitor global crypto and AI markets with a specific focus on how these technologies impact African economies.',
  },
  {
    id: 'dobuygoods',
    title: 'Dobuygoods',
    tagline: 'Buy & Sell. Pay with Crypto.',
    description: 'Buy & Sell. Pay with Crypto. A marketplace for used electronics and general goods — bridging African commerce with digital asset transactions.',
    longDescription: 'Dobuygoods is a crypto-powered marketplace where Africans can buy and sell used electronics, gadgets, and general goods using digital assets. We are bridging the gap between Africa\'s booming second-hand economy and the global digital payments revolution.',
    icon: 'ShoppingCart',
    category: 'Commerce',
    color: '#00C2FF',
    externalLink: 'https://dobuygoods.rpnmore.com',
    features: [
      'Buy & sell with Bitcoin, USDT, and more',
      'Used electronics marketplace',
      'General goods listings',
      'Escrow-protected crypto transactions',
      'Ghana & West Africa focused',
      'Mobile-first experience',
    ],
    additionalInfo: 'Dobuygoods solves a critical pain point: millions of Africans hold crypto but have limited ways to spend it locally. We created a marketplace that accepts digital assets natively, giving crypto holders real purchasing power in their own communities.',
  },
  {
    id: 'signupghana',
    title: 'SignupGhana',
    tagline: 'Branding & Visual Marketing in Ghana',
    description: 'Branding & Visual Marketing in Ghana. Complete brand identity, 3D signage, LED screen advertising, and corporate merchandise.',
    longDescription: 'SignupGhana is Ghana\'s premier branding and visual marketing agency. We create complete brand identities, fabricate 3D signage, produce LED screen advertising campaigns, and deliver corporate merchandise for businesses across Ghana and West Africa.',
    icon: 'Palette',
    category: 'Branding',
    color: '#A855F7',
    externalLink: 'https://signupghana.rpnmore.com',
    features: [
      'Complete brand identity design',
      '3D signage fabrication & installation',
      'LED screen advertising campaigns',
      'Corporate merchandise & uniforms',
      'Billboard & outdoor advertising',
      'Business card & print design',
    ],
    additionalInfo: 'SignupGhana serves businesses ranging from local SMEs to major corporations. Our team combines creative design talent with modern fabrication technology to deliver signage and branding that stands out in Ghana\'s competitive market.',
  },
  {
    id: 'biskaken',
    title: 'Biskaken Auto',
    tagline: 'Trusted Automotive Repair & Services',
    description: 'Trusted Automotive Repair & Services. Professional, reliable, and expert vehicle maintenance — because not everything is digital, yet.',
    longDescription: 'Biskaken Auto is a trusted automotive repair and maintenance service operating in Ghana. We provide professional, reliable, and expert vehicle care — from routine maintenance to major repairs. Because while everything else goes digital, your car still needs human hands.',
    icon: 'Wrench',
    category: 'Automotive',
    color: '#EF4444',
    externalLink: 'https://biskakenauto.rpnmore.com',
    features: [
      'Engine diagnostics & repair',
      'Routine maintenance & oil changes',
      'Brake & suspension services',
      'Electrical & AC systems',
      'Body work & painting',
      'Crypto payment accepted',
    ],
    additionalInfo: 'Biskaken Auto integrates the Ripple & More ecosystem by accepting crypto payments — making it one of the few auto shops in Ghana where you can pay for vehicle services using digital assets. Professional service meets the digital economy.',
  },
  {
    id: 'researchclaw',
    title: 'ResearchClaw',
    tagline: 'AI-Powered Research & Automation',
    description: 'AI-Powered Research & Automation. Agentic AI systems, social media automation at scale, and intelligent workflows across all our ventures.',
    longDescription: 'ResearchClaw is the AI engine behind Ripple & More. We build agentic AI systems, automate social media at scale, and design intelligent workflows that power all of our ventures. From automated content generation to deep research pipelines, ResearchClaw is where intelligence meets execution.',
    icon: 'Bot',
    category: 'AI & Automation',
    color: '#10B981',
    externalLink: 'https://researchclaw.rpnmore.com',
    features: [
      'Agentic AI research systems',
      'Social media automation at scale',
      'Intelligent content workflows',
      'Custom AI pipeline development',
      'Multi-platform publishing automation',
      'AI-driven market intelligence',
    ],
    additionalInfo: 'ResearchClaw powers the automation layer for all Ripple & More ventures. Our AI agents monitor markets, generate content, publish across platforms, and surface insights — 24 hours a day, 7 days a week. This is the technology that gives Ripple & More its competitive edge.',
  }
];
