import { Service, Book } from './types';

export const BOOKS: Book[] = [
  {
    id: 'familys-wrath-dragons-fire',
    title: "Family's Wrath, Dragon's Fire",
    description: 'A powerful dream about fire battles, earth obeying, and the strength of forgiveness. When a family attacks, the elements themselves choose sides.',
    price: '$9.99',
    cover: '/images/book-family-wrath.png',
    coverWebpSrcset: '/images/webp/book-family-wrath-400w.webp 400w, /images/webp/book-family-wrath-800w.webp 800w, /images/webp/book-family-wrath-1200w.webp 1200w',
    gumroadUrl: 'https://mmtkeeper.gumroad.com/l/familys-wrath-dragons-fire',
    category: 'Dreams & Spirituality',
    author: 'Ayi-kwaku Odame',
  },
  {
    id: 'naked-through-the-window',
    title: 'Naked Through the Window',
    description: 'A dream about escape, stripping identity, and finding your "bush" - the place where no one can catch you.',
    price: '$7.99',
    cover: '/images/book-naked-window.png',
    coverWebpSrcset: '/images/webp/book-naked-window-400w.webp 400w, /images/webp/book-naked-window-800w.webp 800w, /images/webp/book-naked-window-1200w.webp 1200w',
    gumroadUrl: 'https://mmtkeeper.gumroad.com/l/naked-through-the-window',
    category: 'Dreams & Spirituality',
    author: 'Ayi-kwaku Odame',
  },
  {
    id: 'darkness-light-hidden-states',
    title: 'Darkness, Light, and the Hidden States of Reality',
    description: "For centuries, humans have tried to understand light and darkness. We see light, feel warmth, and measure waves—but what about the absence of light? This book challenges everything you thought you knew about nothingness.",
    price: '$7.99',
    cover: '/images/book-darkness-light-new.png',
    coverWebpSrcset: '/images/webp/book-darkness-light-new-400w.webp 400w, /images/webp/book-darkness-light-new-800w.webp 800w, /images/webp/book-darkness-light-new-1200w.webp 1200w',
    gumroadUrl: 'https://store.rpnmore.com/l/darkness-light-hidden-states',
    category: 'Philosophy & Physics',
    author: 'Ayi-kwaku Odame',
  },
  {
    id: 'african-crypto-playbook',
    title: 'The African Crypto Playbook',
    description: "How Africans can build wealth with cryptocurrency in 2026. A practical, no-fluff guide to buying, holding, and growing digital assets from anywhere on the continent.",
    price: '$9.99',
    cover: 'https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?w=600&h=800&fit=crop',
    gumroadUrl: 'https://store.rpnmore.com/l/african-crypto-playbook',
    category: 'Crypto & Digital Assets',
  },
  {
    id: 'ai-tools-african-entrepreneurs',
    title: 'AI Tools for African Entrepreneurs',
    description: '5 AI tools that can 10x your business productivity. Real tools, real use cases, and step-by-step guides tailored for African businesses.',
    price: '$7.99',
    cover: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=800&fit=crop',
    gumroadUrl: 'https://store.rpnmore.com/l/ai-tools-african-entrepreneurs',
    category: 'AI & Productivity',
  },
  {
    id: 'start-small-grow-smart',
    title: 'Start Small, Grow Smart',
    description: "The Ripple & More philosophy in a book. Learn how to build digital wealth starting from zero — no thousands needed, just commitment and the right framework.",
    price: '$5.99',
    cover: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=600&h=800&fit=crop',
    gumroadUrl: 'https://store.rpnmore.com/l/start-small-grow-smart',
    category: 'Philosophy & Finance',
  },
  {
    id: 'techafrik-beginner-guide',
    title: 'TechAfrik Beginner\'s Guide',
    description: "Everything you need to know to get started with blockchain, AI, and digital tech as an African. No prior knowledge required.",
    price: '$4.99',
    cover: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=800&fit=crop',
    gumroadUrl: 'https://store.rpnmore.com/l/techafrik-beginners-guide',
    category: 'Tech Education',
  },
];

export const SERVICES: Service[] = [
  {
    id: 'ai-customer-agent',
    title: 'AI Customer Agent',
    tagline: '24/7 AI Employee for Your Business',
    description: 'We install AI agents that handle customer support on WhatsApp, Telegram, and Web. Never miss a lead. Respond instantly. Work while you sleep.',
    longDescription: 'AI Customer Agent is a 24/7 AI employee for your business. It responds to customer inquiries instantly on WhatsApp, Telegram, and Web. It qualifies leads, answers questions, books appointments, and processes payments. You get a fully-trained AI employee that never sleeps, never takes breaks, and handles unlimited conversations.',
    icon: 'Bot',
    category: 'AI Services',
    color: '#10B981',
    features: [
      '24/7 customer support on WhatsApp & Telegram',
      'Instant lead qualification',
      'Appointment booking automation',
      'Payment collection integration',
      'Multi-language support',
      'Analytics dashboard',
    ],
    pricing: {
      setup: '$500',
      monthly: '$99-499',
    },
    additionalInfo: 'Setup includes configuration for your business, training on your products/services, and integration with your existing systems. Monthly fee depends on conversation volume and channels.',
  },
  {
    id: 'fast-web-apps',
    title: 'Fast Web Apps',
    tagline: 'Deploy in 24 Hours',
    description: 'Full-stack web applications deployed fast. React, Node.js, databases, Docker. From idea to live in one day.',
    longDescription: 'Fast Web Apps delivers production-ready web applications in 24 hours. We use modern stacks (React, TypeScript, Node.js, PostgreSQL) and Docker deployment. Perfect for MVPs, landing pages, dashboards, and internal tools. You get a working app, deployed, and ready for users.',
    icon: 'Zap',
    category: 'Development',
    color: '#F5A623',
    features: [
      'Full-stack: React + Node.js + Database',
      'Docker deployment on your server',
      'Responsive design (mobile-first)',
      'API integrations',
      'Admin dashboard included',
      'Source code delivered',
    ],
    pricing: {
      setup: '$200-1000',
      monthly: 'Optional hosting',
    },
    additionalInfo: 'We can build simple apps in 24 hours, complex apps in 2-5 days. All code is delivered to you. We can deploy on your server or provide hosting.',
  },
  {
    id: 'workflow-automation',
    title: 'Workflow Automation',
    tagline: 'n8n + Make.com Setup',
    description: 'Automate repetitive tasks. Connect your apps. Save hours every week. We build it, you enjoy the free time.',
    longDescription: 'Workflow Automation sets up n8n and Make.com workflows that connect your apps and automate repetitive tasks. From social media posting to lead capture to invoice generation — we build the automation, you save hours every week.',
    icon: 'Workflow',
    category: 'Automation',
    color: '#6366F1',
    features: [
      'n8n workflow setup',
      'Make.com automation',
      'Connect 1000+ apps',
      'Custom triggers and actions',
      'Error handling & logging',
      'Documentation included',
    ],
    pricing: {
      setup: '$300-1000',
      monthly: 'Optional maintenance',
    },
    additionalInfo: 'We audit your current processes, identify automation opportunities, and build workflows that save you time. Most clients recover the setup cost within the first month.',
  },
  {
    id: 'techafrik',
    title: 'TechAfrik',
    tagline: 'AI & Blockchain Media for Africa',
    description: 'AI & Blockchain Media for Africa. Delivering tech education, news, and insights across Telegram, WhatsApp, TikTok, Instagram, LinkedIn & X.',
    longDescription: 'TechAfrik is the leading AI and blockchain media platform for Africa. We deliver daily tech education, breaking news, and deep insights to thousands of Africans across every major social platform — Telegram, WhatsApp, TikTok, Instagram, LinkedIn, and X. Our mission is to make blockchain and AI literacy accessible to every African, regardless of background or location.',
    icon: 'Cpu',
    category: 'Media & Education',
    color: '#F5A623',
    externalLink: 'https://techafrik.rpnmore.com',
    features: [
      'Daily AI & blockchain news across 6 platforms',
      'Crypto education for African beginners',
      'Market analysis & trading insights',
      'Community of 10,000+ African tech enthusiasts',
      'Telegram & WhatsApp broadcast channels',
      'TikTok & Instagram video education',
    ],
    additionalInfo: 'TechAfrik operates 24/7 and publishes multiple updates per day across all channels. Our team of researchers and analysts monitor global crypto and AI markets with a specific focus on how these technologies impact African economies.',
  },
  {
    id: 'dobuygoods',
    title: 'Dobuygoods',
    tagline: 'Buy & Sell. Pay with Crypto.',
    description: 'Buy & Sell. Pay with Crypto. A marketplace for used electronics and general goods — bridging African commerce with digital asset transactions.',
    longDescription: 'Dobuygoods is a crypto-powered marketplace where Africans can buy and sell used electronics, gadgets, and general goods using digital assets. We are bridging the gap between Africa\'s booming second-hand economy and the global digital payments revolution.',
    icon: 'ShoppingCart',
    category: 'Commerce',
    color: '#00C2FF',
    externalLink: 'https://dobuygoods.rpnmore.com',
    features: [
      'Buy & sell with Bitcoin, USDT, and more',
      'Used electronics marketplace',
      'General goods listings',
      'Escrow-protected crypto transactions',
      'Ghana & West Africa focused',
      'Mobile-first experience',
    ],
    additionalInfo: 'Dobuygoods solves a critical pain point: millions of Africans hold crypto but have limited ways to spend it locally. We created a marketplace that accepts digital assets natively, giving crypto holders real purchasing power in their own communities.',
  },
  {
    id: 'signupghana',
    title: 'SignupGhana',
    tagline: 'Branding & Visual Marketing in Ghana',
    description: 'Branding & Visual Marketing in Ghana. Complete brand identity, 3D signage, LED screen advertising, and corporate merchandise.',
    longDescription: 'SignupGhana is Ghana\'s premier branding and visual marketing agency. We create complete brand identities, fabricate 3D signage, produce LED screen advertising campaigns, and deliver corporate merchandise for businesses across Ghana and West Africa.',
    icon: 'Palette',
    category: 'Branding',
    color: '#A855F7',
    externalLink: 'https://signupghana.rpnmore.com',
    features: [
      'Complete brand identity design',
      '3D signage fabrication & installation',
      'LED screen advertising campaigns',
      'Corporate merchandise & uniforms',
      'Billboard & outdoor advertising',
      'Business card & print design',
    ],
    additionalInfo: 'SignupGhana serves businesses ranging from local SMEs to major corporations. Our team combines creative design talent with modern fabrication technology to deliver signage and branding that stands out in Ghana\'s competitive market.',
  },
  {
    id: 'biskaken',
    title: 'Biskaken Auto',
    tagline: 'Trusted Automotive Repair & Services',
    description: 'Trusted Automotive Repair & Services. Professional, reliable, and expert vehicle maintenance — because not everything is digital, yet.',
    longDescription: 'Biskaken Auto is a trusted automotive repair and maintenance service operating in Ghana. We provide professional, reliable, and expert vehicle care — from routine maintenance to major repairs. Because while everything else goes digital, your car still needs human hands.',
    icon: 'Wrench',
    category: 'Automotive',
    color: '#EF4444',
    externalLink: 'https://biskakenauto.rpnmore.com',
    features: [
      'Engine diagnostics & repair',
      'Routine maintenance & oil changes',
      'Brake & suspension services',
      'Electrical & AC systems',
      'Body work & painting',
      'Crypto payment accepted',
    ],
    additionalInfo: 'Biskaken Auto integrates the Ripple & More ecosystem by accepting crypto payments — making it one of the few auto shops in Ghana where you can pay for vehicle services using digital assets. Professional service meets the digital economy.',
  },
  {
    id: 'researchclaw',
    title: 'ResearchClaw',
    tagline: 'AI-Powered Research & Automation',
    description: 'AI-Powered Research & Automation. Agentic AI systems, social media automation at scale, and intelligent workflows across all our ventures.',
    longDescription: 'ResearchClaw is the AI engine behind Ripple & More. We build agentic AI systems, automate social media at scale, and design intelligent workflows that power all of our ventures. From automated content generation to deep research pipelines, ResearchClaw is where intelligence meets execution.',
    icon: 'Bot',
    category: 'AI & Automation',
    color: '#10B981',
    externalLink: 'https://researchclaw.rpnmore.com',
    features: [
      'Agentic AI research systems',
      'Social media automation at scale',
      'Intelligent content workflows',
      'Custom AI pipeline development',
      'Multi-platform publishing automation',
      'AI-driven market intelligence',
    ],
    additionalInfo: 'ResearchClaw powers the automation layer for all Ripple & More ventures. Our AI agents monitor markets, generate content, publish across platforms, and surface insights — 24 hours a day, 7 days a week. This is the technology that gives Ripple & More its competitive edge.',
  }
];


// Blog Posts for SEO and Content Marketing
export const BLOG_POSTS = [
  {
    id: 'ai-customer-agents-ghana',
    title: 'How AI Customer Agents Are Replacing Support Teams in Ghana',
    excerpt: 'Discover how Ghanaian businesses are saving $50K+ annually by deploying AI employees that handle customer support 24/7 on WhatsApp and Telegram.',
    content: 'Full blog content here...',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200\u0026h=600\u0026fit=crop',
    date: '2026-04-18',
    author: 'Kk',
    tags: ['AI', 'Ghana', 'Customer Service', 'Automation'],
  },
  {
    id: 'african-crypto-playbook',
    title: 'The African Crypto Playbook: Building Wealth with Digital Assets in 2026',
    excerpt: 'A comprehensive guide to buying, holding, and growing cryptocurrency wealth from anywhere in Africa. Real strategies, real results.',
    content: 'Full blog content here...',
    imageUrl: 'https://images.unsplash.com/photo-1620321023374-d1a68fbc720d?w=1200\u0026h=600\u0026fit=crop',
    date: '2026-04-17',
    author: 'Kk',
    tags: ['Crypto', 'Africa', 'Wealth Building', 'Web3'],
  },
  {
    id: '24-hour-web-apps',
    title: 'From Idea to Live in 24 Hours: Our Web App Development Process',
    excerpt: 'See how we deploy production-ready web applications in 24 hours using React, Node.js, and Docker. Speed without sacrificing quality.',
    content: 'Full blog content here...',
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1200\u0026h=600\u0026fit=crop',
    date: '2026-04-16',
    author: 'Kk',
    tags: ['Web Development', 'MVP', 'React', 'Startup'],
  },
  {
    id: 'workflow-automation-case-study',
    title: 'How One Ghanaian Company Scaled Without Hiring: Automation Case Study',
    excerpt: 'Inside story: How we helped a Ghanaian SME automate 80% of their operations and scale revenue 3x without adding headcount.',
    content: 'Full blog content here...',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200\u0026h=600\u0026fit=crop',
    date: '2026-04-15',
    author: 'Kk',
    tags: ['Automation', 'Case Study', 'Ghana', 'Business Growth'],
  },
];
